### ISSUE TITLE
Error fs.readFile not a function

### ISSUE THREAD

**Issue by vlatkoIT** [vandie/isProfanity#2]
Hi buddy,
I appreciate your effort to do something which from docs' perspective looks very good, yet I couldn't use it in practice. I used the isprofanity function as validation parameter for my vuejs project, but I got console error that **fs.readFile function is not recognized**. I tried to include/require also fs, but the error stayed the same.

I'm not so proficient in nodejs matter, moreover I use npm packages for non-nodejs projects. Any thoughts or ideas how I can solve or examine this issue. 
Regards

**Comment by vandie** [comment]
Hey.

From a quick google search it would seem it is a recurring problem with VueJS and fs.
This is unfortunate as currently, isProfanity requires fs to load in data.
I may at some point add a second way to load in data but I'm not really sure I can help you at the moment.

Apologies
Mike.
